### ISSUE TITLE
style of the art?

### ISSUE THREAD

**Issue by erenarkangil** [njanakiev/openstreetmap-heatmap#4]
Hi,

Is that a style-of-the-art repo? Then i would really like to see how you processed dataset .

Cheers !

**Comment by njanakiev** [comment]
Hello @Erenhub, do you mean state of the art? In [utils_osm.py](https://github.com/njanakiev/openstreetmap-heatmap/blob/master/utils_osm.py), you can see how I collected and processed the data. I also wrote an article on that topic: [Loading Data from OpenStreetMap with Python and the Overpass API](https://janakiev.com/blog/openstreetmap-with-python-and-overpass-api/). For more information check the README.md. Feel free to let me know if anything is unclear

**Comment by erenarkangil** [comment]
yes that was exactly what i  meant, sorry :) 

The code gives me a beautiful framework of germany map with its nodes, however what i really interested in was impressive 3d images in blender.

i am sorry if it is so obvious but it is my first time with Blender then i am going to ask that:

Why blender console does not see overpy module? i specifically installed it into Blender's python enviroment. i am sharing screenshots. thank you so much for your reply !! :)

![1ed](https://user-images.githubusercontent.com/47353633/88823540-e04f0f80-d1cd-11ea-8663-0dc43f3fa947.png)
![Unti2tled](https://user-images.githubusercontent.com/47353633/88823553-e34a0000-d1cd-11ea-925b-a17c7277e55d.png)

**Comment by njanakiev** [comment]
This is sometimes difficult to debug, have a look at [Using Anaconda in Blender](https://janakiev.com/blog/using-anaconda-in-blender/). And make sure to have the same Python version as in Blender. I am closing the issue now, feel free to reopen it in case something is unclear.
